apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: kafka-pacman-producer
  name: kafka-pacman-producer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-pacman-producer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-pacman-producer
    spec:
      containers:
      - image: tbaums/kafka-pacman-producer:latest
        imagePullPolicy: Always
        name: kafka-pacman-producer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: BROKER_SERVICE
          value: kafka-kafka-0.kafka-svc:9092
        - name: MESSAGES_PER_BATCH
          value: '10000'
        - name: PACMAN_JOBS_TOPIC
          value: a8
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
status: {}
